export const HttpStatus = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
  FAILED_TO_FETCH: 0,
}

export const ENDPOINT =
  process.env.NEXT_PUBLIC_ENDPOINT || 'http://127.0.0.1:4000'

export enum Method {
  GRAPHICAL = 1,
  BISECTION = 2,
  FALSE_POSITION = 3,
  ONE_POINT_ITERATION = 4,
  NEWTON = 5,
  SECANT = 6,
  //
  CRAMER_RULE = 7,
  GAUSSIAN_ELIMINATION = 8,
  GAUSS_JORDAN_ELIMINATION = 9,
  MATRIX_INVERSION = 10,
  LU_DECOMPOSITION = 11,
  JACOBI_ITERATION = 12,
  GAUSS_SEIDEL_ITERATION = 13,
  CONJUGATE_GRADIENT = 14,
  //
  NEWTON_DIVIDED_DIFFERENCE = 15,
  LAGRANGE_INTERPOLATION = 16,
  SPLINE_INTERPOLATION = 17,
  //
  SIMPLE_REGRESSION = 18,
  MULTIPLE_REGRESSION = 19,
  //
  TRAPEZOIDAL_RULE = 20,
  COMPOSITE_TRAPEZOIDAL_RULE = 21,
  SIMPSON_RULE = 22,
  COMPOSITE_SIMPSON_RULE = 23,
  //
  NUMERICAL_DIFFERENTIATION = 24,
}

export enum Problem {
  ROOT = 1,
  LINEAR_ALGEBRA = 2,
  INTERPOLATION = 3,
  EXTRAPOLATION = 4,
  INTEGRATION = 5,
  DIFFERENTIATION = 6,
}
